language: python

python:
    - "3.6.7"

install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install codeclimate-test-reporter

script:
    - coverage run --source=app -m pytest && coverage report
    - coveralls

branches:
    only:
      - develop

after_success:
    - coveralls
    - codeclimate-test-reporter
    - codecov --token=86f54247-4d57-4a02-a384-e5c1fe44b3b7
